config/routes.rb
Localpoll::Application.routes.draw do

  resources :polls, :only => :show do
    resource :results, :only => :show
  end

  resource :post_codes, :only => :show

  resources :constituency, :only => :show, :path => "" do
    resources :local_poll, :only => :show, :path => "" do
      resource :vote, :only => :show, :controller => :votes
      resource :votes, :only => :create
      resource :results, :only => :show, :controller => :local_results
    end
  end

  root :to => "homepage#show"

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  attr_accessible :link, :name, :political_party_id

  belongs_to :political_party
  belongs_to :local_poll
  has_many :votes

  scope :with_political_party, where("political_party_id IS NOT NULL")

  def affilliation
    political_party ? political_party.name : "Independent"
  end

end

app/models/constituency.rb
class Constituency < ActiveRecord::Base
  attr_accessible :name, :ons_code

  has_many :local_polls
  has_many :postcodes

  def to_param
    ons_code
  end

end

app/models/local_poll.rb
class LocalPoll < ActiveRecord::Base
  attr_accessible :constituency_id, :name

  belongs_to :poll
  belongs_to :constituency
  has_many :candidates
  has_many :votes

end

app/models/political_party.rb
class PoliticalParty < ActiveRecord::Base
  attr_accessible :name

  has_many :candidates
  has_many :votes, :through => :candidates

  def votes_in(poll)
    votes.joins(:local_poll).where("local_polls.poll_id" => poll)
  end

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :name

  has_many :local_polls
  has_many :candidates, :through => :local_polls
  has_many :votes, :through => :local_polls

  def political_parties
    PoliticalParty.find(candidates.with_political_party.uniq.pluck(:political_party_id))
  end

  def independent_votes
    votes.joins(:candidate).where(:candidates => {:political_party_id => nil})
  end

  def nil_votes
    votes.where(:candidate_id => nil)
  end

end

app/models/postcode.rb
class Postcode < ActiveRecord::Base
  attr_accessible :constituency_id, :name

  belongs_to :constituency
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :candidate_id, :local_poll_id

  belongs_to :candidate, :counter_cache => true
  belongs_to :local_poll

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  private

  def find_constituency
    @constituency = Constituency.find_by_ons_code!(params[:constituency_id])
  end

  def find_local_poll
    @local_poll = @constituency.local_polls.find(params[:local_poll_id])
  end


end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def show
  end

end

app/controllers/local_poll_controller.rb
class LocalPollController < ApplicationController

  def show

    constituency = Constituency.find_by_ons_code!(params[:constituency_id])
    @local_poll = constituency.local_polls.find(params[:id])

  end

end

app/controllers/local_results_controller.rb
class LocalResultsController < ApplicationController

  def show
    find_constituency
    find_local_poll

  end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

end

app/controllers/post_codes_controller.rb
class PostCodesController < ApplicationController

  def show

    post_code = Postcode.find_by_name!(params[:postcode])
    constituency = post_code.constituency
    latest_local_poll = constituency.local_polls.last

    redirect_to constituency_local_poll_path(constituency, latest_local_poll)


  end

  rescue_from(ActiveRecord::RecordNotFound) {

    render 'not_found', :status => 404
  }

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def show
    @poll = Poll.find(params[:poll_id])
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def show
    find_constituency
    find_local_poll

    @vote = @local_poll.votes.new

    render 'new'
  end

  def create
    find_constituency
    find_local_poll

    @vote = @local_poll.votes.new
    @vote.candidate = @local_poll.candidates.find_by_id(params[:vote][:candidate_id])
    @vote.save!
    redirect_to constituency_local_poll_results_path(@constituency, @local_poll)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/show.html.erb
<% content_for :title, "Local Poll" %>


<article>
  <header><h1>Local Poll</h1></header>

  <ol>
    <li>Find out who's standing in your local constituency</li>
    <li>Vote in our unscientific poll</li>
    <li>See the poll results for your area</li>
  </ol>

  <p class="call-to-action">Look up your constituency by post code:</p>

  <%= form_tag post_codes_path, :method => :get, :class => "post-code-lookup" do %>
    <%= text_field_tag :postcode, nil, :placeholder => "ZZ9 ZZA", :class => "post-code", :maxlength => 10 %>
    <%= submit_tag "Go" %>
  <% end %>

</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Local Poll - <%= yield :title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Local Poll", root_path, :class => "site-name" %>

  <%= yield %>

</body>
</html>

app/views/local_poll/show.html.erb
<% content_for :title, @local_poll.name %>

<article>
  <header><h1>Candidates</h1></header>

  <ul>
    <% @local_poll.candidates.each do |candidate| %>
      <%= content_tag "li" do %>
        <%= content_tag "span", candidate.name, :class => :name %>
        <%= content_tag "span", candidate.affilliation, :class => :affilliation %>
        <%= link_to "Website", candidate.link if candidate.link? %>
      <% end %>
    <% end %>
  </ul>

  <%= link_to "Live here? Vote in our unscientific poll", constituency_local_poll_vote_path(@local_poll.constituency, @local_poll), :class => "action-button" %>

  <span class="or">or</span>

  <span class="alternative-action"><%= link_to "view results", constituency_local_poll_results_path(@local_poll.constituency, @local_poll) %></span>


</article>

app/views/local_results/show.html.erb
<% content_for :title, "Results for " + @local_poll.name %>


<article>
  <header><h1>Results for <%= @local_poll.name %></h1></header>

  <ul>
    <% @local_poll.candidates.each do |candidate| %>
      <%= content_tag "li" do %>
        <%= content_tag "span", candidate.name, :class => :name %>
        <%= content_tag "span", candidate.affilliation, :class => :affilliation %>
        <%= content_tag "span", candidate.votes.size, :class => "vote-count" %>
      <% end %>
    <% end %>
    <%= content_tag "li" do %>
      None of the Above: <%= @local_poll.votes.where(:candidate_id => nil).count %>
    <% end %>
  </ul>

  <%= link_to "View national results", poll_results_path(@local_poll.poll), :class => "alternative-action" %>

</article>

app/views/post_codes/not_found.html.erb
<article>
  <header><h1>Postcode not found</h1></header>

  <p>Sorry, we couldn't find that postcode.</p>

</article>

app/views/results/show.html.erb
<% content_for :title, "Results for " + @poll.name %>

<article>
  <header><h1>Results for <%= @poll.name %></h1></header>

  <ul>
    <% @poll.political_parties.each do |political_party| %>
      <%= content_tag "li" do %>
        <%= content_tag "span", political_party.name, :class => :name %>
        <%= political_party.votes_in(@poll).size %>
      <% end %>
    <% end %>
    <%= content_tag "li" do %>
      Independent candidates <%= @poll.independent_votes.size %>
    <% end %>
    <%= content_tag "li" do %>
      'None of the above' votes <%= @poll.nil_votes.size %>
    <% end %>
  </ul>


</article>

app/views/votes/new.html.erb
<% content_for :title, "Vote in " + @local_poll.name %>


<article>
  <header><h1>Vote in <%= @local_poll.name %></h1></header>

  <%= form_for @vote, :url => constituency_local_poll_votes_path(@local_poll.constituency, @local_poll), :html => {:class => "vote"} do |f| %>

    <div class="vote-options">
      <% @local_poll.candidates.each do |candidate| %>
        <div class="vote-option">
          <%= f.radio_button :candidate_id, candidate.id %>
          <%= content_tag "span", candidate.name, :class => "option-name" %>
          <%= content_tag "span", candidate.affilliation, :class => :affilliation %>
        </div>
      <% end %>
      <div class="vote-option">
        <%= f.radio_button :candidate_id, "0" %>
        <%= content_tag "span", "None of the above.", :class => "nil-vote option-name" %>
        <span class="affilliation"></span>
      </div>
    </div>

    <%= f.submit "Vote", :class => "vote" %>

  <% end %>

</article>